openapi: 3.0.0
info:
  title: Movie-Quotes
  description: API
  version: 0.1.9

servers:
  - url: https://movie-quotes-back-production.up.railway.app/api
    description: production server
  - url: http://localhost:3000/api
    description: local server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /register:
    post:
      tags:
        - Auth
      requestBody:
        description: user registration request
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                name:
                  type: string
                password:
                  type: string
                confirmPassword:
                  type: string
                email:
                  type: string
                backlink:
                  type: string
      responses:
        "201":
          description: user register successfully
  /verify:
    post:
      tags:
        - Auth
      requestBody:
        description: verify email
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                hash:
                  type: string
      responses:
        "200":
          description: user verify successfully
  /login:
    post:
      tags:
        - Auth
      requestBody:
        description: user login
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: user login successfully
  /recovery:
    post:
      tags:
        - Auth
      requestBody:
        description: password recovery
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                email:
                  type: string
                backLink:
                  type: string
      responses:
        "200":
          description: check your email
  /reset:
    post:
      tags:
        - Auth
      requestBody:
        description: password reset
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                password:
                  type: string
                confirmPassword:
                  type: string
                hash:
                  type: string
      responses:
        "200":
          description: user password update successfully
  /user/avatar/{userId}:
    put:
      parameters:
        - in: path
          name: userId
          schema:
            type: string
          required: true
      tags:
        - User
      security:
        - bearerAuth: []
      requestBody:
        description: add avatar
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                avatar:
                  type: string
                  format: binary
      responses:
        "200":
          description: avatar uploaded
  /user/emails/{id}:
    post:
      parameters:
        - in: path
          name: userId
          schema:
            type: string
          required: true
      tags:
        - User
      security:
        - bearerAuth: []
      requestBody:
        description: add email
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: binary
      responses:
        "200":
          description: avatar uploaded
  /user/{id}:
    put:
      parameters:
        - in: path
          name: userId
          schema:
            type: string
          required: true
      tags:
        - User
      security:
        - bearerAuth: []
      requestBody:
        description: password reset
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                name:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: user password update successfully
